---
- name: Install virtualenv package
  apt:
    name: python-virtualenv
    state: present
    update_cache: yes
    cache_valid_time: "{{ apt_cache_time }}"

- name: Create virtualenv
  command: virtualenv --python={{ venv_python }} {{ venv }}
  args:
    creates: "{{ venv }}"
